Data Preprocessing Tools

Importing the libraries

In [73]:
import os
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

Importing the dataset

In [74]:
path = os.path.join(os.getcwd(), 'Data.csv')
dataset = pd.read_csv(path)
x = dataset.iloc[:, :-1].values #independent variables and all rows and columns except the last one
y = dataset.iloc[:, -1].values #dependent variable and all rows and only the last column

In [ ]:
#pd.isna(dataset).sum() #check for missing data
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [76]:
print(y)

['No' 'Yes' 'No' 'No' 'Yes' 'Yes' 'No' 'Yes' 'No' 'Yes']


Taking care of missing data

In [77]:
from sklearn.impute import SimpleImputer
imputer = SimpleImputer(missing_values=np.nan,strategy='mean') #replace missing values with the mean of the column
imputer.fit(x[:, 1:3]) #fit the imputer to the matrix x and only columns 1 and 2 
x[:, 1:3] = imputer.transform(x[:, 1:3]) #transform the matrix x and only columns 1 and 2

In [93]:
print(x)


[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding categorical data

Encoding the independent variable

In [79]:
from sklearn.compose import ColumnTransformer #encode the categorical data
from sklearn.preprocessing import OneHotEncoder #encode the categorical data
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [0])], remainder='passthrough') #transformers=[(what to do, what to do it to, what columns to do it to)], remainder='passthrough' means keep the columns that are not transformed
x = np.array(ct.fit_transform(x)) #fit the column transformer to the matrix x and transform it

In [80]:
print(x)

[[1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [0.0 1.0 0.0 30.0 54000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 35.0 58000.0]
 [0.0 0.0 1.0 38.77777777777778 52000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


Encoding the dependent variable

In [81]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
y = le.fit_transform(y) #fit the label encoder to y and transform it    #no need to reshape y because it is a dependent variable    #no need to use np.array because y is already a numpy array 

In [82]:
print(y)

[0 1 0 0 1 1 0 1 0 1]


Splitting the dataset into the training set and test set

In [83]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 1) #split the data into training and testing sets   #random_state is the seed for the random number generator     #test_size is the proportion of the data that is in the test set    #train_size is the proportion of the data that is in the training set   #shuffle=True shuffles the data before splitting it


In [84]:
print(X_train)

[[0.0 0.0 1.0 38.77777777777778 52000.0]
 [0.0 1.0 0.0 40.0 63777.77777777778]
 [1.0 0.0 0.0 44.0 72000.0]
 [0.0 0.0 1.0 38.0 61000.0]
 [0.0 0.0 1.0 27.0 48000.0]
 [1.0 0.0 0.0 48.0 79000.0]
 [0.0 1.0 0.0 50.0 83000.0]
 [1.0 0.0 0.0 35.0 58000.0]]


In [85]:
print(X_test)

[[0.0 1.0 0.0 30.0 54000.0]
 [1.0 0.0 0.0 37.0 67000.0]]


In [86]:
print(y_train)

[0 1 0 0 1 1 0 1]


In [87]:
print(y_test)

[0 1]


Feature Scaling

In [88]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()   #standardize the features
X_train[:, 3:] = sc.fit_transform(X_train[:, 3:]) #fit the standard scaler to the matrix X_train and transform it
X_test[:, 3:] = sc.transform(X_test[:, 3:]) #transform the matrix X_test

In [89]:
print(X_train)

[[0.0 0.0 1.0 -0.19159184384578545 -1.0781259408412425]
 [0.0 1.0 0.0 -0.014117293757057777 -0.07013167641635372]
 [1.0 0.0 0.0 0.566708506533324 0.633562432710455]
 [0.0 0.0 1.0 -0.30453019390224867 -0.30786617274297867]
 [0.0 0.0 1.0 -1.9018011447007988 -1.420463615551582]
 [1.0 0.0 0.0 1.1475343068237058 1.232653363453549]
 [0.0 1.0 0.0 1.4379472069688968 1.5749910381638885]
 [1.0 0.0 0.0 -0.7401495441200351 -0.5646194287757332]]


In [90]:
print(X_test)

[[0.0 1.0 0.0 -1.4661817944830124 -0.9069571034860727]
 [1.0 0.0 0.0 -0.44973664397484414 0.2056403393225306]]
